Repository apache/skywalking-rocketbot-ui, pull requests merged in 2019-10, with the labels that each got.

#165 add feature apache/skywaking#96
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/views/components/trace/d3-trace.js
  src/views/components/trace/trace-detail-chart-list.vue
Labels: enhancement

#166 Fix bug && Optimize code structure
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/views/components/trace/trace-detail-chart-list.vue
  src/views/components/trace/trace-search.vue
Labels: bug, enhancement

#164 fix issue apache/skywalking#3588 .
  src/store/modules/dashboard/modules/dashboard-data-query.ts
  src/store/modules/dashboard/source/endpoint.ts
  src/store/modules/dashboard/source/index.ts
  src/views/components/dashboard/charts/chart-sankey.vue
Labels: bug

#167 fix ci warring Exceeds maximum line length of 120
  src/views/components/trace/trace-detail-chart-list.vue
Labels: bug

#168 fix not show instance language
  src/graph/fragments/option.ts
Labels: bug

#171 Fix bug: language initialization failed
  src/main.ts
Labels: bug

#174 Feature: node detail display in topo circle-chart view.
  src/views/components/topology/radial.vue
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo-services.vue
Labels: enhancement
