Repository apache/skywalking-rocketbot-ui, pull requests merged in 2019-04, with the labels that each got.

#83 remove release-docs and license.
  release-docs/LICENSE
  release-docs/licenses/LICENSE-axios
  release-docs/licenses/LICENSE-d3
  release-docs/licenses/LICENSE-d3-array
  release-docs/licenses/LICENSE-d3-axis
  release-docs/licenses/LICENSE-d3-brush
  release-docs/licenses/LICENSE-d3-chord
  release-docs/licenses/LICENSE-d3-collection
  release-docs/licenses/LICENSE-d3-color
  release-docs/licenses/LICENSE-d3-contour
  release-docs/licenses/LICENSE-d3-dispatch
  release-docs/licenses/LICENSE-d3-drag
  release-docs/licenses/LICENSE-d3-dsv
  release-docs/licenses/LICENSE-d3-ease
  release-docs/licenses/LICENSE-d3-force
  release-docs/licenses/LICENSE-d3-format
  release-docs/licenses/LICENSE-d3-geo
  release-docs/licenses/LICENSE-d3-hierarchy
  release-docs/licenses/LICENSE-d3-interpolate
  release-docs/licenses/LICENSE-d3-path
  release-docs/licenses/LICENSE-d3-polygon
  release-docs/licenses/LICENSE-d3-quadtree
  release-docs/licenses/LICENSE-d3-queue
  release-docs/licenses/LICENSE-d3-random
  release-docs/licenses/LICENSE-d3-request
  release-docs/licenses/LICENSE-d3-scale
  release-docs/licenses/LICENSE-d3-scale-chromatic
  release-docs/licenses/LICENSE-d3-selection
  release-docs/licenses/LICENSE-d3-shape
  release-docs/licenses/LICENSE-d3-time
  release-docs/licenses/LICENSE-d3-time-format
  release-docs/licenses/LICENSE-d3-timer
  release-docs/licenses/LICENSE-d3-tip
  release-docs/licenses/LICENSE-d3-transition
  release-docs/licenses/LICENSE-d3-voronoi
  release-docs/licenses/LICENSE-d3-zoom
  release-docs/licenses/LICENSE-dayjs
  release-docs/licenses/LICENSE-echarts
  release-docs/licenses/LICENSE-popperjs
  release-docs/licenses/LICENSE-vue
  release-docs/licenses/LICENSE-vue-class-component
  release-docs/licenses/LICENSE-vue-datepicker-local
  release-docs/licenses/LICENSE-vue-i18n
  release-docs/licenses/LICENSE-vue-property-decorator
  release-docs/licenses/LICENSE-vue-router
  release-docs/licenses/LICENSE-vuex
  release-docs/licenses/LICENSE-vuex-class
  release-docs/licenses/LICENSE-zrender
Labels: license

#84 Update: remove login api tag
  src/views/containers/login.vue
Labels: bug

#85 Update readme.
  README.md
  vue.config.js
Labels: enhancement

#86 Update: Fix bug
  package.json
  src/components/index.ts
  src/components/noty/bootstrap-v4.css
  src/components/noty/index.ts
  src/components/noty/noty.css
  src/views/components/alarm/alarm-tool.vue
  src/views/components/dashboard/charts/chart-slow.vue
  src/views/components/dashboard/charts/chart-through.vue
  src/views/components/dashboard/charts/chart-trace-db.vue
  src/views/components/dashboard/charts/chart-trace.vue
  src/views/components/dashboard/dashboard-comp.vue
  src/views/components/topology/topo.vue
  src/views/components/trace/trace-detail-chart-tree.vue
  src/views/components/trace/trace-search.vue
  src/views/components/trace/trace-table.vue
  src/views/containers/alarm.vue
  src/views/containers/dashboard.vue
Labels: bug

#87 Update: add header
  src/components/noty/bootstrap-v4.css
  src/components/noty/noty.css
Labels: bug

#88 Update: update trace-list
  src/views/components/trace/trace-search.vue
Labels: enhancement
