Repository apache/skywalking-rocketbot-ui, pull requests merged in 2019-08, with the labels that each got.

#129 display trace data in table
  package-lock.json
  src/assets/index.ts
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/assets/svg/table.svg
  src/store/modules/global/index.ts
  src/utils/tooltip.scss
  src/utils/tooltip.ts
  src/views/components/trace/trace-chart-table/collapse.gif
  src/views/components/trace/trace-chart-table/expand.gif
  src/views/components/trace/trace-chart-table/trace-container.vue
  src/views/components/trace/trace-chart-table/trace-item.vue
  src/views/components/trace/trace-chart-table/trace.scss
  src/views/components/trace/trace-detail-chart-table.vue
  src/views/components/trace/trace-detail-chart-tree.vue
  src/views/components/trace/trace-detail.vue
  src/views/components/trace/trace-table.vue
Labels: enhancement

#131 fix topology page js bug
  src/store/modules/topology/index.ts
Labels: enhancement

#135 Add license.
  src/views/components/trace/trace-chart-table/trace-container.vue
  src/views/components/trace/trace-chart-table/trace-item.vue
  src/views/components/trace/trace-chart-table/trace.scss
  src/views/components/trace/trace-detail-chart-table.vue
Labels: bug

#140 fix rk-date-calendar.vue error "TypeError: handler.apply is not a function"
  src/components/rk-date-calendar.vue
Labels: bug

#139 fix "The "topo-services" component did not update the data in time after modifying the time range on the topology page."
  src/utils/comparison.ts
  src/views/components/topology/topo-services.vue
Labels: enhancement

#143 Trace detail optimize
  src/store/modules/trace/index.ts
  src/store/mutation-types.ts
  src/views/components/trace/d3-trace.js
  src/views/components/trace/trace-detail-chart-list.vue
  src/views/components/trace/trace-detail-chart-table.vue
  src/views/components/trace/trace-search.vue
  src/views/components/trace/trace-table.vue
Labels: enhancement

#128 Update: add radial chart
  src/main.ts
  src/views/components/topology/radial.vue
  src/views/components/topology/topo-aside.vue
Labels: enhancement

#144 Fix dashboard Endpoint Slow charts.
  src/store/modules/dashboard/template/endpoint-template.ts
Labels: bug

#145 Fix ui bug & Add trace completion
  src/components/rk-header.vue
  src/views/components/trace/trace-chart-table/collapse.gif
  src/views/components/trace/trace-chart-table/expand.gif
  src/views/components/trace/trace-chart-table/trace-container.vue
  src/views/components/trace/trace-chart-table/trace-item.vue
  src/views/components/trace/trace-detail-chart-list.vue
  src/views/components/trace/trace-detail-chart-table.vue
  src/views/components/trace/trace-detail-chart-tree.vue
  src/views/components/trace/trace-table.vue
  src/views/containers/dashboard.vue
  vue.config.js
Labels: bug, enhancement

#146 Fix language chinese & span error status
  src/views/components/trace/d3-trace-tree.js
  src/views/components/trace/trace-detail-chart-list.vue
  src/views/components/trace/trace-detail-chart-table.vue
  src/views/components/trace/trace-detail-chart-tree.vue
Labels: bug, enhancement
