Repository apache/skywalking-rocketbot-ui, pull requests merged in 2019-06, with the labels that each got.

#115 Update: update utc & duration
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/components/rk-footer.vue
  src/components/rk-header.vue
  src/store/modules/index.ts
  src/store/mutation-types.ts
  src/views/components/topology/topo.vue
  src/views/components/trace/trace-detail.vue
  src/views/components/trace/trace-search.vue
  src/views/components/trace/trace-table.vue
Labels: bug, enhancement

#107 Update: remove login page
  src/router.ts
Labels: enhancement

#118 remove logout
  src/components/rk-header.vue
Labels: bug

#121 Update: fix topo percent bug && add GC count chart
  src/graph/fragments/topology.ts
  src/store/modules/dashboard/modules/dashboard-data.ts
  src/store/modules/dashboard/source/index.ts
  src/store/modules/dashboard/source/instance.ts
  src/store/modules/dashboard/template/instance-template.ts
  src/views/components/dashboard/charts/chart-count.vue
  src/views/components/dashboard/charts/index.ts
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo-response.vue
Labels: enhancement

#122 Update: fix percent charts bug
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/views/components/dashboard/charts/chart-line.vue
  src/views/components/topology/topo-response.vue
Labels: bug

#124 Fix some issue
  README.md
  src/views/components/topology/topo.vue
Labels: bug
