Repository apache/skywalking-rocketbot-ui, pull requests merged in 2019-12, with the labels that each got.

#218 Feat: remove element-ui
  package.json
  src/App.vue
  src/components/rk-back.vue
  src/components/rk-button.vue
  src/components/rk-footer.vue
  src/main.ts
  src/router.ts
  src/shims-tsx.d.ts
  src/store/index.ts
  src/store/modules/topology/index.ts
  src/views/components/alarm/alarm-tool.vue
  src/views/components/dashboard/dashboard-comp.vue
  src/views/components/dashboard/tool-bar.vue
  src/views/components/topology/radial.vue
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo-chart.vue
  src/views/components/topology/topo-response.vue
  src/views/components/topology/topo.vue
  src/views/components/trace/trace-search.vue
  src/views/containers/alarm.vue
  src/views/containers/dashboard.vue
  src/views/containers/endpoint-survey-window.vue
  src/views/containers/instances-survey-window.vue
  src/views/containers/topology.vue
  src/views/containers/trace.vue
Labels: dependencies, enhancement

#220 Revert "Feat: remove element-ui (#218)"
  package.json
  src/App.vue
  src/components/rk-back.vue
  src/components/rk-button.vue
  src/components/rk-footer.vue
  src/main.ts
  src/router.ts
  src/shims-tsx.d.ts
  src/store/index.ts
  src/store/modules/topology/index.ts
  src/views/components/alarm/alarm-tool.vue
  src/views/components/dashboard/dashboard-comp.vue
  src/views/components/dashboard/tool-bar.vue
  src/views/components/topology/radial.vue
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo-chart.vue
  src/views/components/topology/topo-response.vue
  src/views/components/topology/topo.vue
  src/views/components/trace/trace-search.vue
  src/views/containers/alarm.vue
  src/views/containers/dashboard.vue
  src/views/containers/endpoint-survey-window.vue
  src/views/containers/instances-survey-window.vue
  src/views/containers/topology.vue
  src/views/containers/trace.vue
Labels: bug

#219 Sync timezone with oap server
  package-lock.json
  src/graph/fragments/option.ts
  src/graph/query/option.ts
  src/main.ts
  src/store/modules/global/index.ts
  src/utils/localtime.ts
Labels: enhancement

#221 Enhanced topology left-click display service indicators
  src/main.ts
  src/utils/localtime.ts
  src/views/components/dashboard/dashboard-comp.vue
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo.vue
Labels: enhancement

#222 fix alarm unable to search
  src/views/components/alarm/alarm-tool.vue
  src/views/containers/alarm.vue
Labels: bug

#223 fix: update drawer for modal and click nodes
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo.vue
  src/views/containers/endpoint-survey-window.vue
  src/views/containers/instances-survey-window.vue
Labels: bug

#225 fix topo reload
  src/views/components/topology/topo-aside.vue
Labels: bug

#226 fix topo can't drag
  src/views/components/topology/topo-aside.vue
Labels: bug

#217 Use URL parameters to visit specified trace
  src/views/components/trace/trace-search.vue
Labels: enhancement

#227 Add Armeria logo and fix npm warning
  .github/workflows/nodejs.yml
  src/views/components/topology/assets/ARMERIA.png
  src/views/components/topology/topo.vue
  src/views/components/trace/trace-search.vue
Labels: enhancement

#231 update event-bus type
  src/event-bus.ts
  src/types/vue.d.ts
Labels: enhancement

#233 Feat instance dependency
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/components/rk-echarts.vue
  src/event-bus.ts
  src/graph/fragments/topology.ts
  src/graph/query/topology.ts
  src/store/modules/topology/index.ts
  src/store/mutation-types.ts
  src/views/components/topology/dependency-sankey.vue
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo-detect-point.vue
  src/views/components/topology/topo-instance-dependency.vue
  src/views/components/topology/topo-services.vue
  src/views/components/topology/topo.vue
Labels: enhancement

#234 fix: update drawer
  src/views/components/topology/dependency-sankey.vue
  src/views/components/topology/topo-detect-point.vue
  src/views/components/topology/topo-instance-dependency.vue
Labels: bug

#235 fix topo click node display redundant client and server element
  src/graph/query/topology.ts
  src/views/components/topology/topo-detect-point.vue
Labels: bug

#236 fix topo metric transformation
  src/views/components/topology/topo-detect-point.vue
Labels: bug

#237 Fix add missing comma
  src/views/components/topology/topo-detect-point.vue
Labels: bug

#238 Fix line chart for instance dependency
  src/store/modules/topology/index.ts
  src/views/components/topology/chart-line.vue
  src/views/components/topology/topo-instance-dependency.vue
Labels: bug

#239 refactor(topo): remove old line chart
  src/store/modules/topology/index.ts
  src/views/components/topology/chart-line.vue
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo-detect-point.vue
  src/views/components/topology/topo-response.vue
Labels: enhancement
