Repository apache/skywalking-rocketbot-ui, pull requests merged in 2020-11, with the labels that each got.

#369 feat: remove node-sass, use dart-sass
  package-lock.json
  package.json
Labels: dependencies

#367 Removed "Les Miserables" from radial chart in topology.
  src/views/components/topology/radial.vue
Labels: bug

#373 Change "Service filter" to "Service group"
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/graph/fragments/option.ts
Labels: enhancement

#375 Replace serviceFilter with serviceGroup
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/store/modules/dashboard/dashboard-data-layout.ts
  src/store/modules/dashboard/mutation-types.ts
  src/types/dashboard.d.ts
  src/views/components/dashboard/tool-bar-btns.vue
  src/views/components/dashboard/tool-bar.vue
  src/views/components/dashboard/tool-group.vue
  src/views/containers/dashboard.vue
Labels: enhancement

#372 Moved magic strings to constants file
  src/constants/constant.ts
  src/utils/datetime.ts
  src/utils/timeFormat.ts
  src/views/components/dashboard/charts/chart-edit.vue
  src/views/components/dashboard/dashboard-item.vue
  src/views/containers/dashboard.vue
  src/views/containers/topology/endpoint/index.vue
  src/views/containers/topology/instance/index.vue
  src/views/containers/topology/topology.vue
Labels: chore

#383 Add the Promise dropdown option
  src/store/modules/log/index.ts
Labels: bug
