Repository apache/skywalking-rocketbot-ui, pull requests merged in 2020-06, with the labels that each got.

#302 Feat: Query and manage templates
  src/graph/fragments/dashboard.ts
  src/graph/fragments/option.ts
  src/graph/index.ts
  src/graph/query/dashboard.ts
  src/graph/query/option.ts
  src/store/modules/dashboard/dashboard-data-layout.ts
  src/store/modules/dashboard/dashboard-data.ts
  src/store/modules/dashboard/dashboard-option.ts
  src/store/modules/dashboard/mutation-types.ts
  src/store/modules/topology/index.ts
  src/template/database-template.ts
  src/template/endpoint-template.ts
  src/template/global-template.ts
  src/template/instance-template.ts
  src/template/service-template.ts
  src/template/topology-endpoint-template.ts
  src/template/topology-instance-template.ts
  src/types/dashboard.d.ts
  src/views/components/dashboard/dashboard-item.vue
  src/views/containers/dashboard.vue
  src/views/containers/topology/endpoint/endpoints-survey.vue
  src/views/containers/topology/endpoint/index.vue
  src/views/containers/topology/instance/index.vue
  src/views/containers/topology/instance/instances-survey.vue
  src/views/containers/topology/topology.vue
Labels: enhancement

#304 Bugfix: Edit dashboard
  src/views/components/dashboard/dashboard-item.vue
  src/views/containers/dashboard.vue
Labels: bug

#288 Feat:Import and export the configuration file for the dashboard layout
  src/assets/styles/lib.scss
  src/store/modules/dashboard/dashboard-data-layout.ts
  src/store/modules/dashboard/dashboard-data-query.ts
  src/store/modules/dashboard/mutation-types.ts
  src/utils/readFile.ts
  src/utils/saveFile.ts
  src/views/components/dashboard/dashboard-item.vue
  src/views/components/dashboard/tool-bar-btns.vue
  src/views/components/dashboard/tool-bar.vue
  src/views/components/dashboard/tool-group.vue
  src/views/components/dashboard/tool-nav.vue
  src/views/constant.ts
  src/views/containers/dashboard.vue
  src/views/containers/topology/endpoint/endpoints-survey.vue
  src/views/containers/topology/endpoint/index.vue
  src/views/containers/topology/instance/index.vue
  src/views/containers/topology/instance/instances-survey.vue
  src/views/containers/topology/topology.vue
Labels: enhancement

#303 add influxdb-java plugin
  src/views/components/topology/assets/INFLUXDB.png
Labels: enhancement

#307 Bugfix: Dashboard templates
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/store/modules/dashboard/dashboard-data-query.ts
  src/views/components/dashboard/charts/chart-edit.vue
  src/views/components/dashboard/tool-bar-btns.vue
  src/views/components/dashboard/tool-group.vue
  src/views/containers/dashboard.vue
Labels: bug

#310 Feat: Improve 8.0.0
  src/store/modules/dashboard/dashboard-data-query.ts
  src/store/modules/topology/index.ts
  src/store/mutation-types.ts
  src/views/components/dashboard/charts/chart-edit.vue
  src/views/components/dashboard/dashboard-item.vue
  src/views/components/dashboard/tool-group.vue
  src/views/components/topology/topo-services.vue
  src/views/containers/topology/endpoint/endpoints-survey.vue
  src/views/containers/topology/endpoint/index.vue
  src/views/containers/topology/instance/index.vue
  src/views/containers/topology/instance/instances-survey.vue
  src/views/containers/topology/topology.vue
Labels: enhancement

#311 Bugfix: version8.0.0
  src/components/rk-sidebox.vue
  src/store/modules/dashboard/dashboard-data-layout.ts
  src/store/modules/topology/index.ts
  src/store/mutation-types.ts
  src/views/components/dashboard/charts/chart-heatmap.vue
  src/views/components/dashboard/dashboard-item.vue
  src/views/components/dashboard/tool-group.vue
  src/views/containers/topology/endpoint/endpoints-survey.vue
  src/views/containers/topology/instance/instances-survey.vue
Labels: bug, enhancement

#312 Bugfix: service and instance in topology
  src/views/components/dashboard/dashboard-item.vue
  src/views/constant.ts
  src/views/containers/dashboard.vue
  src/views/containers/topology/endpoint/index.vue
  src/views/containers/topology/instance/index.vue
  src/views/containers/topology/topology.vue
Labels: bug

#309 Add PHP logo in topo
  src/views/components/topology/assets/PHP.png
Labels: enhancement

#313 Bugfix: Unavailable services/database
  src/store/modules/dashboard/dashboard-data-layout.ts
  src/store/modules/dashboard/dashboard-data-query.ts
  src/store/modules/dashboard/mutation-types.ts
  src/store/mutation-types.ts
  src/views/components/dashboard/dashboard-item.vue
  src/views/components/dashboard/tool-nav.vue
  src/views/containers/dashboard.vue
Labels: bug

#314 Feat: add trace table scroll-x and method-th drag
  src/views/components/common/trace-chart-table/trace-container.vue
  src/views/components/common/trace-chart-table/trace-item.vue
  src/views/components/common/trace-chart-table/trace.scss
  src/views/components/common/trace-detail-chart-table.vue
Labels: enhancement

#315 Feat: update thread-stack
  src/views/components/common/trace-chart-table/trace.scss
  src/views/components/profile/profile-container.vue
  src/views/components/profile/profile-detail-chart-table.vue
  src/views/components/profile/profile-item.vue
  src/views/components/profile/profile.scss
Labels: enhancement

#316 Fix: profile display bug
  src/views/components/profile/profile-container.vue
  src/views/components/profile/profile-item.vue
  src/views/components/profile/profile.scss
Labels: bug

#319 Feat: Add chart options to components
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/views/components/dashboard/charts/chart-area.vue
  src/views/components/dashboard/charts/chart-bar.vue
  src/views/components/dashboard/charts/chart-edit.vue
  src/views/components/dashboard/charts/chart-line.vue
  src/views/components/dashboard/charts/constant.ts
  src/views/components/dashboard/charts/index.ts
Labels: enhancement

#320 Feat: Add status color in trace table
  src/views/components/common/trace-chart-table/trace-item.vue
  src/views/components/profile/task-list.vue
Labels: enhancement
