Repository apache/skywalking-rocketbot-ui, pull requests merged in 2020-12, with the labels that each got.

#386 Fix the local cache tag
  src/views/components/trace/trace-search.vue
Labels: bug

#387 fix: dashboard metrics name and optimize code
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/graph/query/log.ts
  src/graph/query/option.ts
  src/views/components/dashboard/charts/chart-num.vue
  src/views/components/dashboard/charts/chart-slow.vue
  src/views/components/log/log-detail-table.vue
  src/views/components/log/log-table/log-constant.ts
  src/views/components/log/log-table/log-item.vue
  src/views/components/log/log-table/log-table.vue
Labels: bug

#388 fix: auto reload dashbaord
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/components/rk-header.vue
Labels: bug

#389 Fix: Profile and Trace table style
  src/views/components/common/trace-chart-table/trace-item.vue
  src/views/components/profile/profile-item.vue
Labels: bug

#390 feat: separation Log and Dashboard selector data
  src/store/modules/dashboard/dashboard-option.ts
  src/store/modules/log/index.ts
  src/store/mutation-types.ts
  src/views/components/log/log-bar.vue
Labels: bug, enhancement

#391 fix: trace instance selector
  src/store/modules/dashboard/dashboard-option.ts
  src/store/modules/trace/index.ts
  src/views/components/trace/trace-search.vue
Labels: bug

#392 Remove travis CI
  .travis.yml
Labels: chore

#393 Polish readme.
  README.md
Labels: chore

#394 fix: chart tooltips style
  src/views/components/dashboard/charts/chart-bar.vue
  src/views/components/dashboard/charts/chart-line.vue
Labels: bug

#396 refactor: dashboard query constant
  src/graph/fragments/dashboard.ts
  src/graph/query/dashboard.ts
  src/store/modules/dashboard/constant-metrics-query.ts
  src/store/modules/dashboard/dashboard-data-query.ts
Labels: enhancement

#398 feat: implement refreshing data for topology by updating date
  src/views/components/topology/chart-line.vue
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo-detect-point.vue
  src/views/components/topology/topo-services.vue
  src/views/containers/topology/topology.vue
Labels: enhancement

#399 Feat: Implement group selector in the topology
  src/graph/fragments/option.ts
  src/views/components/topology/radial.vue
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo-detect-point.vue
  src/views/components/topology/topo-endpoint-dependency.vue
  src/views/components/topology/topo-group/create-group.vue
  src/views/components/topology/topo-group/group-item.vue
  src/views/components/topology/topo-select.vue
  src/views/components/topology/topo-services.vue
Labels: enhancement

#404 fix: render topology of all services
  src/views/components/topology/topo-services.vue
Labels: bug
