Repository apache/skywalking-rocketbot-ui, pull requests merged in 2020-05, with the labels that each got.

#292 Fix: Topology first visit bug.
  src/views/components/topology/topo-services.vue
Labels: bug

#296 Feat: Update alarm scope
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/views/components/alarm/alarm-tool.vue
Labels: enhancement

#298 Create .asf.yaml to mute the noises from PR/comments
  .asf.yaml
Labels: chore

#300 Fix wrong indentations in .asf.yaml
  .asf.yaml
Labels: chore

#301 Bugfix: dashboard common selectors
  src/store/modules/dashboard/dashboard-option.ts
  src/views/components/dashboard/dashboard-item.vue
Labels: bug
