Repository apache/skywalking-rocketbot-ui, pull requests merged in 2021-03, with the labels that each got.

#432 feat: search endpoints with keywords
  src/store/modules/global/selectors.ts
  src/views/components/dashboard/tool-bar-endpoint-select.vue
  src/views/components/dashboard/tool-bar.vue
  src/views/components/profile/profile-detail-chart-table.vue
  src/views/containers/topology/instance/index.vue
Labels: bug, enhancement

#434 fix: update pageSize on logs page
  src/views/components/log/log-bar.vue
Labels: bug

#435 build: update echarts version to 5.0.0
  package-lock.json
  package.json
  src/components/rk-echarts.vue
  src/views/components/dashboard/charts/chart-heatmap.vue
  src/views/components/topology/dependency-sankey.vue
  vue.config.js
Labels: chore

#439 build: fix resolved url for vue-property-decorator
  package-lock.json
  package.json
Labels: bug, chore

#436 fix: update instance dependency
  src/store/modules/topology/index.ts
  src/views/components/dashboard/charts/chart-sankey.vue
  src/views/components/topology/dependency-sankey.vue
  src/views/components/topology/radial.vue
Labels: bug

#440 fix: update instance dependency
  src/store/modules/topology/index.ts
Labels: bug

#441 feat: show instance attributes
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/components/rk-sidebox.vue
  src/views/components/dashboard/tool-bar/tool-bar-btns.vue
  src/views/components/dashboard/tool-bar/tool-bar-endpoint-select-opt.vue
  src/views/components/dashboard/tool-bar/tool-bar-endpoint-select.vue
  src/views/components/dashboard/tool-bar/tool-bar-select.vue
  src/views/components/dashboard/tool-bar/tool-bar.vue
  src/views/components/log/log-bar.vue
  src/views/containers/dashboard.vue
  src/views/containers/topology/endpoint-dependency/index.vue
  src/views/containers/topology/endpoint/index.vue
  src/views/containers/topology/instance/index.vue
Labels: enhancement

#444 Grammar fix
  README.md
Labels: chore

#443 Fix log pages tags column not updated
  src/views/components/log/log-table/log-service-item.vue
Labels: bug

#446 Fix the problem that the footer and topology group is shaded when the topology radiation is displayed.
  src/components/rk-footer.vue
  src/views/components/topology/topo-group/index.vue
Labels: enhancement

#448 When the topology radiation chart is displayed, the corresponding button should be highlighted.
  src/views/components/topology/topo-aside.vue
Labels: enhancement

#454 Topology optimization of two services that call each other.
  src/views/components/topology/chart/topo.vue
Labels: enhancement
