Repository apache/skywalking-rocketbot-ui, pull requests merged in 2021-04, with the labels that each got.

#459 feat: extend table chart
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/views/components/dashboard/charts/chart-edit.vue
  src/views/components/dashboard/charts/chart-table.vue
  src/views/components/dashboard/dashboard-comp.vue
  src/views/components/dashboard/dashboard-item.vue
Labels: enhancement

#452 feat: implement Events in dashboard
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/components/rk-select.vue
  src/constants/constant.ts
  src/graph/fragments/dashboard.ts
  src/graph/query/dashboard.ts
  src/main.ts
  src/store/modules/dashboard/dashboard-data.ts
  src/store/modules/dashboard/mutation-types.ts
  src/store/modules/global/index.ts
  src/store/modules/global/selectors.ts
  src/types/dashboard.d.ts
  src/utils/dateFormat.ts
  src/views/components/dashboard/charts/chart-bar.vue
  src/views/components/dashboard/charts/chart-heap.vue
  src/views/components/dashboard/charts/chart-heatmap.vue
  src/views/components/dashboard/charts/chart-line.vue
  src/views/components/dashboard/charts/chart-sankey.vue
  src/views/components/dashboard/constant.ts
  src/views/components/dashboard/dashboard-comp.vue
  src/views/components/dashboard/dashboard-item.vue
  src/views/components/dashboard/tool-bar/dashboard-events.vue
  src/views/components/dashboard/tool-bar/tool-bar-btns.vue
  src/views/components/dashboard/tool-bar/tool-bar.vue
  src/views/components/dashboard/tool-group.vue
  src/views/components/dashboard/tool-nav.vue
  src/views/components/log/log-bar.vue
  src/views/components/log/log-conditions.vue
  src/views/components/log/log-service-detail.vue
  src/views/components/profile/profile-task.vue
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo-endpoint-dependency.vue
  src/views/components/trace/trace-search.vue
  src/views/containers/dashboard.vue
  src/views/containers/topology/endpoint/index.vue
  src/views/containers/topology/instance/index.vue
  vue.config.js
Labels: enhancement

#460 fix: update table style
  src/views/components/dashboard/charts/chart-table.vue
  src/views/components/dashboard/dashboard-item.vue
Labels: enhancement

#461 Fix typo
  src/assets/lang/zh.ts
Labels: chore

#463 fix: render multiple metrics in the dashboard
  src/views/components/dashboard/dashboard-item.vue
Labels: bug

#464 fix: update groups
  src/views/components/topology/topo-services.vue
Labels: bug

#478 When creating service groups in the topology, it is better if the service names are sorted.
  src/views/components/topology/topo-group/index.vue
Labels: enhancement

#480 fix: update style of endpoint dependency
  src/components/rk-sidebox.vue
  src/views/components/dashboard/dashboard-item.vue
  src/views/components/dashboard/tool-bar/dashboard-events.vue
  src/views/components/log/log-conditions.vue
  src/views/components/topology/radial.vue
  src/views/components/topology/topo-aside.vue
  src/views/components/topology/topo-detect-point.vue
  src/views/components/topology/topo-endpoint-dependency.vue
  src/views/components/topology/topo-group/group-item.vue
  src/views/components/topology/topo-group/index.vue
  src/views/components/topology/topo-instance-dependency.vue
  src/views/components/topology/topo-services.vue
  src/views/components/trace/trace-table.vue
  src/views/containers/topology/endpoint-dependency/index.vue
Labels: bug

#474 endpoint component enhanced in trace-search
  src/assets/styles/lib.scss
  src/store/modules/trace/index.ts
  src/views/components/trace/trace-search.vue
Labels: enhancement

#475 Solve the problem that traceId stored in localstorage cannot be deleted
  src/views/components/trace/trace-search.vue
Labels: bug

#482 feat: enhance the custom content of tooltips on dashboard
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/views/components/dashboard/charts/chart-edit.vue
  src/views/components/dashboard/dashboard-item.vue
  src/views/components/trace/trace-search.vue
  src/views/containers/dashboard.vue
Labels: enhancement

#483 feat: Support search and visualize alarms with tags
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/graph/fragments/alarm.ts
  src/types/alarm.d.ts
  src/views/components/alarm/alarm-table.vue
  src/views/components/alarm/alarm-tool.vue
  src/views/components/common/condition-tags.vue
  src/views/components/common/index.ts
  src/views/components/log/log-conditions.vue
  src/views/components/log/log-service-detail.vue
  src/views/components/trace/trace-search.vue
Labels: enhancement

#484 fix: update configuration on dashboard
  src/views/components/alarm/alarm-tool.vue
  src/views/components/dashboard/charts/chart-edit.vue
  src/views/components/dashboard/charts/constant.ts
Labels: bug

#481 Support to configure the maximum number of displayed items
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/store/modules/dashboard/dashboard-data-query.ts
  src/views/components/dashboard/charts/chart-edit.vue
  src/views/components/trace/trace-search.vue
Labels: enhancement
