Repository apache/skywalking-rocketbot-ui, pull requests merged in 2021-01, with the labels that each got.

#407 fix: update utc and sort group
  src/components/rk-footer.vue
  src/views/components/topology/topo-services.vue
Labels: bug, enhancement

#409 fix: update dashboard wrong instance and add a legend for topology
  src/store/modules/dashboard/dashboard-data-query.ts
  src/store/modules/dashboard/dashboard-option.ts
  src/views/components/dashboard/dashboard-item.vue
  src/views/components/topology/chart/topo.vue
  src/views/components/topology/chart/utils/legend.js
  src/views/components/topology/chart/utils/nodeElement.js
  src/views/containers/dashboard.vue
Labels: bug, enhancement

#411 fix: support `=` in the tag value in the trace query page.
  src/views/components/trace/trace-search.vue
  src/views/containers/topology/trace/index.vue
  src/views/containers/trace.vue
Labels: bug

#413 chore: set up license-eye to check license headers
  .github/workflows/nodejs.yml
  .licenserc.yaml
  run.sh
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/types/profile.d.ts
  src/utils/cssHelper.ts
Labels: chore

#414 DashboardItem miss prop `rocketOption`
  src/views/containers/topology/endpoint/endpoints-survey.vue
  src/views/containers/topology/instance/instances-survey.vue
Labels: bug

#420 Feat: implement viewing logs on trace page
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/store/modules/trace/index.ts
  src/store/mutation-types.ts
  src/views/components/common/trace-detail-chart-table.vue
  src/views/components/log/log-service-detail.vue
  src/views/components/log/log-table/log-service-item.vue
  src/views/components/log/log-table/log-table.vue
  src/views/components/trace/trace-detail-chart-list.vue
  src/views/components/trace/trace-detail-chart-tree.vue
  src/views/components/trace/trace-detail.vue
  src/views/components/trace/trace-search.vue
  src/views/components/trace/trace-span-logs.vue
  src/views/components/trace/trace-table.vue
Labels: enhancement

#421 fix: update props of date component
  src/assets/lang/en.ts
  src/components/rk-date-calendar.vue
  src/components/rk-footer-time.vue
  src/graph/query/dashboard.ts
  src/graph/query/log.ts
  src/graph/query/profile.ts
  src/graph/query/topology.ts
  src/views/components/topology/chart/topo.vue
  src/views/components/trace/trace-search.vue
Labels: bug

#422 fix: update query conditions for logs
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/graph/fragments/log.ts
  src/views/components/log/log-bar.vue
  src/views/components/log/log-conditions.vue
  src/views/components/log/log-table/log-constant.ts
  src/views/components/log/log-table/log-service-item.vue
  src/views/components/log/log-table/log-table.vue
  src/views/components/trace/trace-search.vue
Labels: bug, enhancement

#423 fix: update ui for logs
  src/store/modules/log/index.ts
  src/store/mutation-types.ts
  src/views/components/log/log-bar.vue
  src/views/components/log/log-browser-detail.vue
  src/views/components/log/log-conditions.vue
  src/views/components/log/log-service-detail.vue
  src/views/components/log/log-table/log-table.vue
  src/views/components/trace/trace-detail.vue
  src/views/components/trace/trace-search.vue
  src/views/components/trace/trace-span-logs.vue
Labels: bug

#424 fix: update search content for logs
  src/assets/lang/en.ts
  src/assets/lang/zh.ts
  src/views/components/log/log-bar.vue
  src/views/components/log/log-conditions.vue
Labels: bug
