Repository apache/skywalking-rocketbot-ui, pull requests merged in 2021-02, with the labels that each got.

#425 fix: update ui for logs
  src/views/components/common/trace-select.vue
  src/views/components/dashboard/tool-bar-endpoint-select.vue
  src/views/components/dashboard/tool-bar-select.vue
  src/views/components/log/log-bar.vue
  src/views/components/log/log-table/log-service-item.vue
  src/views/containers/topology/trace/trace-select.vue
Labels: bug

#426 fix: update scroller
  src/assets/styles/reset.scss
  src/components/rk-select.vue
  src/views/components/alarm/alarm-select.vue
  src/views/components/common/trace-select.vue
  src/views/components/dashboard/tool-bar-endpoint-select.vue
  src/views/components/dashboard/tool-bar-select.vue
  src/views/components/profile/task-list.vue
  src/views/components/topology/topo-select.vue
  src/views/containers/topology/trace/trace-select.vue
Labels: bug, enhancement

#428 feat: implement searching logs with date
  src/store/modules/global/index.ts
  src/utils/dateFormatStep.ts
  src/views/components/log/log-bar.vue
  src/views/components/log/log-conditions.vue
  src/views/components/log/log-service-detail.vue
  src/views/components/profile/profile-header.vue
  src/views/components/trace/trace-search.vue
Labels: enhancement

#429 Add nodejs 14 compiling
  .github/workflows/nodejs.yml
Labels: chore

#431 fix: clear trace id by clear search conditions
  src/store/modules/log/index.ts
  src/views/components/log/log-conditions.vue
Labels: bug
